#include "game.h"

#include <fonts/mdi.h>

SMARTENUM_DEFINE(_GameCategory, GameCategory)

SMARTENUM_DEFINE(_GameStatus, GameStatus)
const GameStatusInfo game_status[] = {
    [GameStatusNormal] = {.color = {{0.95, 0.95, 0.95, 1.0}}, .icon = mdi_lightning_bolt_circle},
    [GameStatusCompleted] = {.color = {{0.0, 0.87, 0.0, 1.0}}, .icon = mdi_checkbox_marked_circle},
    [GameStatusOnHold] = {.color = {{0.0, 0.5, 0.95, 1.0}}, .icon = mdi_pause_circle},
    [GameStatusAbandoned] = {.color = {{0.87, 0.2, 0.2, 1.0}}, .icon = mdi_close_circle},
    [GameStatusUnchecked] = {.color = {{0.5, 0.5, 0.5, 1.0}}, .icon = mdi_alert_circle},
    [GameStatusCustom] = {.color = {{0.95, 0.5, 0.0, 1.0}}, .icon = mdi_dots_horizontal_circle},
};

SMARTENUM_DEFINE(_GameTag, GameTag)
const GameTagInfo game_tag[] = {
    [GameTag2dGame] = {.text = "2d game"},
    [GameTag2dcg] = {.text = "2dcg"},
    [GameTag3dGame] = {.text = "3d game"},
    [GameTag3dcg] = {.text = "3dcg"},
    [GameTagAdventure] = {.text = "adventure"},
    [GameTagAhegao] = {.text = "ahegao"},
    [GameTagAiCg] = {.text = "ai cg"},
    [GameTagAnalSex] = {.text = "anal sex"},
    [GameTagAnimated] = {.text = "animated"},
    [GameTagAssetAddon] = {.text = "asset-addon"},
    [GameTagAssetAiShoujo] = {.text = "asset-ai-shoujo"},
    [GameTagAssetAnimal] = {.text = "asset-animal"},
    [GameTagAssetAnimation] = {.text = "asset-animation"},
    [GameTagAssetAudio] = {.text = "asset-audio"},
    [GameTagAssetBundle] = {.text = "asset-bundle"},
    [GameTagAssetCharacter] = {.text = "asset-character"},
    [GameTagAssetClothing] = {.text = "asset-clothing"},
    [GameTagAssetDazGen1] = {.text = "asset-daz-gen1"},
    [GameTagAssetDazGen2] = {.text = "asset-daz-gen2"},
    [GameTagAssetDazGen3] = {.text = "asset-daz-gen3"},
    [GameTagAssetDazGen8] = {.text = "asset-daz-gen8"},
    [GameTagAssetDazGen81] = {.text = "asset-daz-gen81"},
    [GameTagAssetDazGen9] = {.text = "asset-daz-gen9"},
    [GameTagAssetDazM4] = {.text = "asset-daz-m4"},
    [GameTagAssetDazV4] = {.text = "asset-daz-v4"},
    [GameTagAssetEnvironment] = {.text = "asset-environment"},
    [GameTagAssetExpression] = {.text = "asset-expression"},
    [GameTagAssetFemale] = {.text = "asset-female"},
    [GameTagAssetHair] = {.text = "asset-hair"},
    [GameTagAssetHdri] = {.text = "asset-hdri"},
    [GameTagAssetHoneySelect] = {.text = "asset-honey-select"},
    [GameTagAssetHoneySelect2] = {.text = "asset-honey-select2"},
    [GameTagAssetKoikatu] = {.text = "asset-koikatu"},
    [GameTagAssetLight] = {.text = "asset-light"},
    [GameTagAssetMale] = {.text = "asset-male"},
    [GameTagAssetMorph] = {.text = "asset-morph"},
    [GameTagAssetNonbinary] = {.text = "asset-nonbinary"},
    [GameTagAssetPlayhome] = {.text = "asset-playhome"},
    [GameTagAssetPlugin] = {.text = "asset-plugin"},
    [GameTagAssetPose] = {.text = "asset-pose"},
    [GameTagAssetProp] = {.text = "asset-prop"},
    [GameTagAssetScene] = {.text = "asset-scene"},
    [GameTagAssetScript] = {.text = "asset-script"},
    [GameTagAssetShader] = {.text = "asset-shader"},
    [GameTagAssetTexture] = {.text = "asset-texture"},
    [GameTagAssetUtility] = {.text = "asset-utility"},
    [GameTagAssetVehicle] = {.text = "asset-vehicle"},
    [GameTagBdsm] = {.text = "bdsm"},
    [GameTagBestiality] = {.text = "bestiality"},
    [GameTagBigAss] = {.text = "big ass"},
    [GameTagBigTits] = {.text = "big tits"},
    [GameTagBlackmail] = {.text = "blackmail"},
    [GameTagBukkake] = {.text = "bukkake"},
    [GameTagCensored] = {.text = "censored"},
    [GameTagCharacterCreation] = {.text = "character creation"},
    [GameTagCheating] = {.text = "cheating"},
    [GameTagCombat] = {.text = "combat"},
    [GameTagCorruption] = {.text = "corruption"},
    [GameTagCosplay] = {.text = "cosplay"},
    [GameTagCreampie] = {.text = "creampie"},
    [GameTagDatingSim] = {.text = "dating sim"},
    [GameTagDilf] = {.text = "dilf"},
    [GameTagDrugs] = {.text = "drugs"},
    [GameTagDystopianSetting] = {.text = "dystopian setting"},
    [GameTagExhibitionism] = {.text = "exhibitionism"},
    [GameTagFantasy] = {.text = "fantasy"},
    [GameTagFemaleProtagonist] = {.text = "female protagonist"},
    [GameTagFemaledomination] = {.text = "female domination"},
    [GameTagFootjob] = {.text = "footjob"},
    [GameTagFurry] = {.text = "furry"},
    [GameTagFutaTrans] = {.text = "futa/trans"},
    [GameTagFutaTransProtagonist] = {.text = "futa/trans protagonist"},
    [GameTagGay] = {.text = "gay"},
    [GameTagGraphicViolence] = {.text = "graphic violence"},
    [GameTagGroping] = {.text = "groping"},
    [GameTagGroupSex] = {.text = "group sex"},
    [GameTagHandjob] = {.text = "handjob"},
    [GameTagHarem] = {.text = "harem"},
    [GameTagHorror] = {.text = "horror"},
    [GameTagHumiliation] = {.text = "humiliation"},
    [GameTagHumor] = {.text = "humor"},
    [GameTagIncest] = {.text = "incest"},
    [GameTagInternalView] = {.text = "internal view"},
    [GameTagInterracial] = {.text = "interracial"},
    [GameTagJapaneseGame] = {.text = "japanese game"},
    [GameTagKineticNovel] = {.text = "kinetic novel"},
    [GameTagLactation] = {.text = "lactation"},
    [GameTagLesbian] = {.text = "lesbian"},
    [GameTagLoli] = {.text = "loli"},
    [GameTagMaleProtagonist] = {.text = "male protagonist"},
    [GameTagMaledomination] = {.text = "male domination"},
    [GameTagManagement] = {.text = "management"},
    [GameTagMasturbation] = {.text = "masturbation"},
    [GameTagMilf] = {.text = "milf"},
    [GameTagMindControl] = {.text = "mind control"},
    [GameTagMobileGame] = {.text = "mobile game"},
    [GameTagMonster] = {.text = "monster"},
    [GameTagMonsterGirl] = {.text = "monster girl"},
    [GameTagMultipleEndings] = {.text = "multiple endings"},
    [GameTagMultiplePenetration] = {.text = "multiple penetration"},
    [GameTagMultipleProtagonist] = {.text = "multiple protagonist"},
    [GameTagNecrophilia] = {.text = "necrophilia"},
    [GameTagNoSexualContent] = {.text = "no sexual content"},
    [GameTagNtr] = {.text = "netorare"},
    [GameTagOralSex] = {.text = "oral sex"},
    [GameTagParanormal] = {.text = "paranormal"},
    [GameTagParody] = {.text = "parody"},
    [GameTagPlatformer] = {.text = "platformer"},
    [GameTagPointClick] = {.text = "point & click"},
    [GameTagPossession] = {.text = "possession"},
    [GameTagPov] = {.text = "pov"},
    [GameTagPregnancy] = {.text = "pregnancy"},
    [GameTagProstitution] = {.text = "prostitution"},
    [GameTagPuzzle] = {.text = "puzzle"},
    [GameTagRape] = {.text = "rape"},
    [GameTagRealPorn] = {.text = "real porn"},
    [GameTagReligion] = {.text = "religion"},
    [GameTagRomance] = {.text = "romance"},
    [GameTagRpg] = {.text = "rpg"},
    [GameTagSandbox] = {.text = "sandbox"},
    [GameTagScat] = {.text = "scat"},
    [GameTagSchoolSetting] = {.text = "school setting"},
    [GameTagSciFi] = {.text = "sci-fi"},
    [GameTagSexToys] = {.text = "sex toys"},
    [GameTagSexualHarassment] = {.text = "sexual harassment"},
    [GameTagShooter] = {.text = "shooter"},
    [GameTagShota] = {.text = "shota"},
    [GameTagSideScroller] = {.text = "side-scroller"},
    [GameTagSimulator] = {.text = "simulator"},
    [GameTagSissification] = {.text = "sissification"},
    [GameTagSlave] = {.text = "slave"},
    [GameTagSleepSex] = {.text = "sleep sex"},
    [GameTagSpanking] = {.text = "spanking"},
    [GameTagStrategy] = {.text = "strategy"},
    [GameTagStripping] = {.text = "stripping"},
    [GameTagSuperpowers] = {.text = "superpowers"},
    [GameTagSwinging] = {.text = "swinging"},
    [GameTagTeasing] = {.text = "teasing"},
    [GameTagTentacles] = {.text = "tentacles"},
    [GameTagTextBased] = {.text = "text based"},
    [GameTagTitfuck] = {.text = "titfuck"},
    [GameTagTrainer] = {.text = "trainer"},
    [GameTagTransformation] = {.text = "transformation"},
    [GameTagTrap] = {.text = "trap"},
    [GameTagTurnBasedCombat] = {.text = "turn based combat"},
    [GameTagTwins] = {.text = "twins"},
    [GameTagUrination] = {.text = "urination"},
    [GameTagVaginalSex] = {.text = "vaginal sex"},
    [GameTagVirgin] = {.text = "virgin"},
    [GameTagVirtualReality] = {.text = "virtual reality"},
    [GameTagVoiced] = {.text = "voiced"},
    [GameTagVore] = {.text = "vore"},
    [GameTagVoyeurism] = {.text = "voyeurism"},
};

SMARTENUM_DEFINE(_GameType, GameType)
const GameTypeInfo game_type[] = {
    [GameTypeADRIFT] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategoryGames},
    [GameTypeFlash] = {.color = {{0.38, 0.38, 0.38, 1.0}}, .category = GameCategoryGames},
    [GameTypeHTML] = {.color = {{0.408, 0.624, 0.22, 1.0}}, .category = GameCategoryGames},
    [GameTypeJava] = {.color = {{0.322, 0.651, 0.69, 1.0}}, .category = GameCategoryGames},
    [GameTypeOthers] = {.color = {{0.545, 0.765, 0.29, 1.0}}, .category = GameCategoryGames},
    [GameTypeQSP] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategoryGames},
    [GameTypeRAGS] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategoryGames},
    [GameTypeRenPy] = {.color = {{0.69, 0.412, 0.91, 1.0}}, .category = GameCategoryGames},
    [GameTypeRPGM] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategoryGames},
    [GameTypeTads] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategoryGames},
    [GameTypeUnity] = {.color = {{0.996, 0.349, 0.004, 1.0}}, .category = GameCategoryGames},
    [GameTypeUnrealEng] = {.color = {{0.051, 0.278, 0.631, 1.0}}, .category = GameCategoryGames},
    [GameTypeWebGL] = {.color = {{0.996, 0.349, 0.004, 1.0}}, .category = GameCategoryGames},
    [GameTypeWolfRPG] = {.color = {{0.298, 0.686, 0.314, 1.0}}, .category = GameCategoryGames},
    [GameTypeCG] = {.color = {{0.875, 0.796, 0.216, 1.0}}, .category = GameCategoryMedia},
    [GameTypeCollection] = {.color = {{0.38, 0.38, 0.38, 1.0}}, .category = GameCategoryMedia},
    [GameTypeComics] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategoryMedia},
    [GameTypeGIF] = {.color = {{0.012, 0.663, 0.957, 1.0}}, .category = GameCategoryMedia},
    [GameTypeManga] = {.color = {{0.059, 0.698, 0.988, 1.0}}, .category = GameCategoryMedia},
    [GameTypePinup] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategoryMedia},
    [GameTypeSiteRip] = {.color = {{0.545, 0.765, 0.29, 1.0}}, .category = GameCategoryMedia},
    [GameTypeVideo] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategoryMedia},
    [GameTypeCheatMod] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategoryMisc},
    [GameTypeMod] = {.color = {{0.729, 0.271, 0.271, 1.0}}, .category = GameCategoryMisc},
    [GameTypeREADME] = {.color = {{0.863, 0.078, 0.235, 1.0}}, .category = GameCategoryMisc},
    [GameTypeRequest] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategoryMisc},
    [GameTypeTool] = {.color = {{0.925, 0.333, 0.333, 1.0}}, .category = GameCategoryMisc},
    [GameTypeTutorial] = {.color = {{0.925, 0.333, 0.333, 1.0}}, .category = GameCategoryMisc},
    [GameTypeMisc] = {.color = {{0.722, 0.69, 0.047, 1.0}}, .category = GameCategoryMisc},
    [GameTypeUnchecked] = {.color = {{0.224, 0.224, 0.224, 1.0}}, .category = GameCategoryMisc},
};
