#include "game.h"

#include <fonts/mdi.h>

SMARTENUM_DEFINE(_GameCategory, GameCategory)

SMARTENUM_DEFINE(_GameStatus, GameStatus)
const GameStatusInfo game_status[1 + GameStatus_COUNT] = {
    [GameStatus_Normal] = {.color = {{0.95, 0.95, 0.95, 1.0}}, .icon = mdi_lightning_bolt_circle},
    [GameStatus_Completed] = {.color = {{0.0, 0.87, 0.0, 1.0}}, .icon = mdi_checkbox_marked_circle},
    [GameStatus_OnHold] = {.color = {{0.0, 0.5, 0.95, 1.0}}, .icon = mdi_pause_circle},
    [GameStatus_Abandoned] = {.color = {{0.87, 0.2, 0.2, 1.0}}, .icon = mdi_close_circle},
    [GameStatus_Unchecked] = {.color = {{0.5, 0.5, 0.5, 1.0}}, .icon = mdi_alert_circle},
    [GameStatus_Custom] = {.color = {{0.95, 0.5, 0.0, 1.0}}, .icon = mdi_dots_horizontal_circle},
};

SMARTENUM_DEFINE(_GameTag, GameTag)
const GameTagInfo game_tag[1 + GameTag_COUNT] = {
    [GameTag_2dGame] = {.text = "2d game"},
    [GameTag_2dcg] = {.text = "2dcg"},
    [GameTag_3dGame] = {.text = "3d game"},
    [GameTag_3dcg] = {.text = "3dcg"},
    [GameTag_Adventure] = {.text = "adventure"},
    [GameTag_Ahegao] = {.text = "ahegao"},
    [GameTag_AiCg] = {.text = "ai cg"},
    [GameTag_AnalSex] = {.text = "anal sex"},
    [GameTag_Animated] = {.text = "animated"},
    [GameTag_AssetAddon] = {.text = "asset-addon"},
    [GameTag_AssetAiShoujo] = {.text = "asset-ai-shoujo"},
    [GameTag_AssetAnimal] = {.text = "asset-animal"},
    [GameTag_AssetAnimation] = {.text = "asset-animation"},
    [GameTag_AssetAudio] = {.text = "asset-audio"},
    [GameTag_AssetBundle] = {.text = "asset-bundle"},
    [GameTag_AssetCharacter] = {.text = "asset-character"},
    [GameTag_AssetClothing] = {.text = "asset-clothing"},
    [GameTag_AssetDazGen1] = {.text = "asset-daz-gen1"},
    [GameTag_AssetDazGen2] = {.text = "asset-daz-gen2"},
    [GameTag_AssetDazGen3] = {.text = "asset-daz-gen3"},
    [GameTag_AssetDazGen8] = {.text = "asset-daz-gen8"},
    [GameTag_AssetDazGen81] = {.text = "asset-daz-gen81"},
    [GameTag_AssetDazGen9] = {.text = "asset-daz-gen9"},
    [GameTag_AssetDazM4] = {.text = "asset-daz-m4"},
    [GameTag_AssetDazV4] = {.text = "asset-daz-v4"},
    [GameTag_AssetEnvironment] = {.text = "asset-environment"},
    [GameTag_AssetExpression] = {.text = "asset-expression"},
    [GameTag_AssetFemale] = {.text = "asset-female"},
    [GameTag_AssetHair] = {.text = "asset-hair"},
    [GameTag_AssetHdri] = {.text = "asset-hdri"},
    [GameTag_AssetHoneySelect] = {.text = "asset-honey-select"},
    [GameTag_AssetHoneySelect2] = {.text = "asset-honey-select2"},
    [GameTag_AssetKoikatu] = {.text = "asset-koikatu"},
    [GameTag_AssetLight] = {.text = "asset-light"},
    [GameTag_AssetMale] = {.text = "asset-male"},
    [GameTag_AssetMorph] = {.text = "asset-morph"},
    [GameTag_AssetNonbinary] = {.text = "asset-nonbinary"},
    [GameTag_AssetPlayhome] = {.text = "asset-playhome"},
    [GameTag_AssetPlugin] = {.text = "asset-plugin"},
    [GameTag_AssetPose] = {.text = "asset-pose"},
    [GameTag_AssetProp] = {.text = "asset-prop"},
    [GameTag_AssetScene] = {.text = "asset-scene"},
    [GameTag_AssetScript] = {.text = "asset-script"},
    [GameTag_AssetShader] = {.text = "asset-shader"},
    [GameTag_AssetTexture] = {.text = "asset-texture"},
    [GameTag_AssetUtility] = {.text = "asset-utility"},
    [GameTag_AssetVehicle] = {.text = "asset-vehicle"},
    [GameTag_Bdsm] = {.text = "bdsm"},
    [GameTag_Bestiality] = {.text = "bestiality"},
    [GameTag_BigAss] = {.text = "big ass"},
    [GameTag_BigTits] = {.text = "big tits"},
    [GameTag_Blackmail] = {.text = "blackmail"},
    [GameTag_Bukkake] = {.text = "bukkake"},
    [GameTag_Censored] = {.text = "censored"},
    [GameTag_CharacterCreation] = {.text = "character creation"},
    [GameTag_Cheating] = {.text = "cheating"},
    [GameTag_Combat] = {.text = "combat"},
    [GameTag_Corruption] = {.text = "corruption"},
    [GameTag_Cosplay] = {.text = "cosplay"},
    [GameTag_Creampie] = {.text = "creampie"},
    [GameTag_DatingSim] = {.text = "dating sim"},
    [GameTag_Dilf] = {.text = "dilf"},
    [GameTag_Drugs] = {.text = "drugs"},
    [GameTag_DystopianSetting] = {.text = "dystopian setting"},
    [GameTag_Exhibitionism] = {.text = "exhibitionism"},
    [GameTag_Fantasy] = {.text = "fantasy"},
    [GameTag_FemaleProtagonist] = {.text = "female protagonist"},
    [GameTag_Femaledomination] = {.text = "female domination"},
    [GameTag_Footjob] = {.text = "footjob"},
    [GameTag_Furry] = {.text = "furry"},
    [GameTag_FutaTrans] = {.text = "futa/trans"},
    [GameTag_FutaTransProtagonist] = {.text = "futa/trans protagonist"},
    [GameTag_Gay] = {.text = "gay"},
    [GameTag_GraphicViolence] = {.text = "graphic violence"},
    [GameTag_Groping] = {.text = "groping"},
    [GameTag_GroupSex] = {.text = "group sex"},
    [GameTag_Handjob] = {.text = "handjob"},
    [GameTag_Harem] = {.text = "harem"},
    [GameTag_Horror] = {.text = "horror"},
    [GameTag_Humiliation] = {.text = "humiliation"},
    [GameTag_Humor] = {.text = "humor"},
    [GameTag_Incest] = {.text = "incest"},
    [GameTag_InternalView] = {.text = "internal view"},
    [GameTag_Interracial] = {.text = "interracial"},
    [GameTag_JapaneseGame] = {.text = "japanese game"},
    [GameTag_KineticNovel] = {.text = "kinetic novel"},
    [GameTag_Lactation] = {.text = "lactation"},
    [GameTag_Lesbian] = {.text = "lesbian"},
    [GameTag_Loli] = {.text = "loli"},
    [GameTag_MaleProtagonist] = {.text = "male protagonist"},
    [GameTag_Maledomination] = {.text = "male domination"},
    [GameTag_Management] = {.text = "management"},
    [GameTag_Masturbation] = {.text = "masturbation"},
    [GameTag_Milf] = {.text = "milf"},
    [GameTag_MindControl] = {.text = "mind control"},
    [GameTag_MobileGame] = {.text = "mobile game"},
    [GameTag_Monster] = {.text = "monster"},
    [GameTag_MonsterGirl] = {.text = "monster girl"},
    [GameTag_MultipleEndings] = {.text = "multiple endings"},
    [GameTag_MultiplePenetration] = {.text = "multiple penetration"},
    [GameTag_MultipleProtagonist] = {.text = "multiple protagonist"},
    [GameTag_Necrophilia] = {.text = "necrophilia"},
    [GameTag_NoSexualContent] = {.text = "no sexual content"},
    [GameTag_Ntr] = {.text = "netorare"},
    [GameTag_OralSex] = {.text = "oral sex"},
    [GameTag_Paranormal] = {.text = "paranormal"},
    [GameTag_Parody] = {.text = "parody"},
    [GameTag_Platformer] = {.text = "platformer"},
    [GameTag_PointClick] = {.text = "point & click"},
    [GameTag_Possession] = {.text = "possession"},
    [GameTag_Pov] = {.text = "pov"},
    [GameTag_Pregnancy] = {.text = "pregnancy"},
    [GameTag_Prostitution] = {.text = "prostitution"},
    [GameTag_Puzzle] = {.text = "puzzle"},
    [GameTag_Rape] = {.text = "rape"},
    [GameTag_RealPorn] = {.text = "real porn"},
    [GameTag_Religion] = {.text = "religion"},
    [GameTag_Romance] = {.text = "romance"},
    [GameTag_Rpg] = {.text = "rpg"},
    [GameTag_Sandbox] = {.text = "sandbox"},
    [GameTag_Scat] = {.text = "scat"},
    [GameTag_SchoolSetting] = {.text = "school setting"},
    [GameTag_SciFi] = {.text = "sci-fi"},
    [GameTag_SexToys] = {.text = "sex toys"},
    [GameTag_SexualHarassment] = {.text = "sexual harassment"},
    [GameTag_Shooter] = {.text = "shooter"},
    [GameTag_Shota] = {.text = "shota"},
    [GameTag_SideScroller] = {.text = "side-scroller"},
    [GameTag_Simulator] = {.text = "simulator"},
    [GameTag_Sissification] = {.text = "sissification"},
    [GameTag_Slave] = {.text = "slave"},
    [GameTag_SleepSex] = {.text = "sleep sex"},
    [GameTag_Spanking] = {.text = "spanking"},
    [GameTag_Strategy] = {.text = "strategy"},
    [GameTag_Stripping] = {.text = "stripping"},
    [GameTag_Superpowers] = {.text = "superpowers"},
    [GameTag_Swinging] = {.text = "swinging"},
    [GameTag_Teasing] = {.text = "teasing"},
    [GameTag_Tentacles] = {.text = "tentacles"},
    [GameTag_TextBased] = {.text = "text based"},
    [GameTag_Titfuck] = {.text = "titfuck"},
    [GameTag_Trainer] = {.text = "trainer"},
    [GameTag_Transformation] = {.text = "transformation"},
    [GameTag_Trap] = {.text = "trap"},
    [GameTag_TurnBasedCombat] = {.text = "turn based combat"},
    [GameTag_Twins] = {.text = "twins"},
    [GameTag_Urination] = {.text = "urination"},
    [GameTag_VaginalSex] = {.text = "vaginal sex"},
    [GameTag_Virgin] = {.text = "virgin"},
    [GameTag_VirtualReality] = {.text = "virtual reality"},
    [GameTag_Voiced] = {.text = "voiced"},
    [GameTag_Vore] = {.text = "vore"},
    [GameTag_Voyeurism] = {.text = "voyeurism"},
};

SMARTENUM_DEFINE(_GameType, GameType)
const GameTypeInfo game_type[1 + GameType_COUNT] = {
    [GameType_ADRIFT] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategory_Games},
    [GameType_Flash] = {.color = {{0.38, 0.38, 0.38, 1.0}}, .category = GameCategory_Games},
    [GameType_HTML] = {.color = {{0.408, 0.624, 0.22, 1.0}}, .category = GameCategory_Games},
    [GameType_Java] = {.color = {{0.322, 0.651, 0.69, 1.0}}, .category = GameCategory_Games},
    [GameType_Others] = {.color = {{0.545, 0.765, 0.29, 1.0}}, .category = GameCategory_Games},
    [GameType_QSP] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategory_Games},
    [GameType_RAGS] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategory_Games},
    [GameType_RenPy] = {.color = {{0.69, 0.412, 0.91, 1.0}}, .category = GameCategory_Games},
    [GameType_RPGM] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategory_Games},
    [GameType_Tads] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategory_Games},
    [GameType_Unity] = {.color = {{0.996, 0.349, 0.004, 1.0}}, .category = GameCategory_Games},
    [GameType_UnrealEng] = {.color = {{0.051, 0.278, 0.631, 1.0}}, .category = GameCategory_Games},
    [GameType_WebGL] = {.color = {{0.996, 0.349, 0.004, 1.0}}, .category = GameCategory_Games},
    [GameType_WolfRPG] = {.color = {{0.298, 0.686, 0.314, 1.0}}, .category = GameCategory_Games},
    [GameType_CG] = {.color = {{0.875, 0.796, 0.216, 1.0}}, .category = GameCategory_Media},
    [GameType_Collection] = {.color = {{0.38, 0.38, 0.38, 1.0}}, .category = GameCategory_Media},
    [GameType_Comics] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategory_Media},
    [GameType_GIF] = {.color = {{0.012, 0.663, 0.957, 1.0}}, .category = GameCategory_Media},
    [GameType_Manga] = {.color = {{0.059, 0.698, 0.988, 1.0}}, .category = GameCategory_Media},
    [GameType_Pinup] = {.color = {{0.129, 0.588, 0.953, 1.0}}, .category = GameCategory_Media},
    [GameType_SiteRip] = {.color = {{0.545, 0.765, 0.29, 1.0}}, .category = GameCategory_Media},
    [GameType_Video] = {.color = {{1.0, 0.596, 0.0, 1.0}}, .category = GameCategory_Media},
    [GameType_CheatMod] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategory_Misc},
    [GameType_Mod] = {.color = {{0.729, 0.271, 0.271, 1.0}}, .category = GameCategory_Misc},
    [GameType_README] = {.color = {{0.863, 0.078, 0.235, 1.0}}, .category = GameCategory_Misc},
    [GameType_Request] = {.color = {{0.827, 0.184, 0.184, 1.0}}, .category = GameCategory_Misc},
    [GameType_Tool] = {.color = {{0.925, 0.333, 0.333, 1.0}}, .category = GameCategory_Misc},
    [GameType_Tutorial] = {.color = {{0.925, 0.333, 0.333, 1.0}}, .category = GameCategory_Misc},
    [GameType_Misc] = {.color = {{0.722, 0.69, 0.047, 1.0}}, .category = GameCategory_Misc},
    [GameType_Unchecked] = {.color = {{0.224, 0.224, 0.224, 1.0}}, .category = GameCategory_Misc},
};
